### ISSUE TITLE
Can someone help me how to create cappi and how to plot the same? 

### ISSUE THREAD

**Issue by hamidrizvi** [MeteoSwiss/pyart#2]

**Comment by jfigui** [comment]
Dear @hamidrizvi ,

Are you using the MeteoSwiss Py-ART or also willing to use Pyrad?
If you use Pyrad have a look first at some of the examples in https://github.com/MeteoSwiss/pyrad-examples

If you use Py-ART only, then the function that you are looking for is: pyart.map.grid_from_radars

Have a look at function plot_cappi in https://github.com/MeteoSwiss/pyrad/blob/master/src/pyrad_proc/pyrad/graph/plots_vol.py

Be aware that this is the MeteoSwiss version of Py-ART. You can find the more popular ARM Py-ART here: https://github.com/ARM-DOE/pyart

I hope that helps. Let us know if you need further help.

**Comment by jfigui** [comment]
Dear @hamidrizvi ,

In https://github.com/MeteoSwiss/pyrad-examples/tree/master/config/processing you can find the config file cfradial_cappi.txt.

It is an example on how to read a CFRadial file and plot a CAPPI using Pyrad. Be aware of the expect file name form and directory structure.

**Comment by jfigui** [comment]
I am closing this issue but feel free to request further help if needed.

Be aware though that we are providing support on a best effort basis
