### ISSUE TITLE
Wrong slice location plotted in gridmapdisplay.py

### ISSUE THREAD

**Issue by katelbach** [MeteoSwiss/pyart#6]
When plotting a slice between two points using the function "plot_latlon_level" in "gridmapdisplay.py", the resulting slice has an erroneous end point when the angle from north between the points is between 90 and 180°.

Changing line 1232 from "if ang > 90.:" to "if ang > 180:" resolves the issue.

**Comment by jfigui** [comment]
@katelbach ,
Thanks for the bug reporting. We are going to have a look at it as soon as possible. @wolfidan , can you make sure that the proposed solution is fine?

**Comment by wolfidan** [comment]
Thank you very much @katelbach  for signaling this.
Couldn't we simplify this part to 

ang = (np.arctan2(ind_2[0]-ind_1[0], ind_2[1]-ind_1[1])*180./np.pi)%360
delta_x = xy_res*np.sin((ang)*np.pi/180.)
delta_y = xy_res*np.cos((ang)*np.pi/180.)
?

**Comment by wolfidan** [comment]
I have corrected this issue in the master and dev branches of pyart. So I am closing it now. Again thank you very much for your feedback @katelbach.
